/**
 * Vercel Serverless Function: Telegram Bot Webhook Handler
 * Path: /api/telegram
 *
 * How it works:
 * - Telegram sends POST requests to https://your-domain.vercel.app/api/telegram
 *   every time a user sends a message or clicks an inline button.
 * - This function processes the update and replies instantly.
 * - No long-polling needed on the server — Telegram pushes to us.
 *
 * The client-side (browser) bot is still used for:
 * - Automatic hazard alerts triggered by the physics simulation
 * - Fault injection notifications
 * These are sent directly from the browser since they depend on live
 * simulation state that only exists in the browser context.
 */

const BOT_TOKEN = '8664722270:AAE7OJYP7Jwn1rV_B0Ty0oHm6RRi-PQZYy4';
const CHAT_ID   = '8984846317';
const API_URL   = `https://api.telegram.org/bot${BOT_TOKEN}`;

async function sendMessage(text, replyMarkup = null) {
  const payload = { chat_id: CHAT_ID, text, parse_mode: 'HTML' };
  if (replyMarkup) payload.reply_markup = replyMarkup;
  const res = await fetch(`${API_URL}/sendMessage`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload)
  });
  return res.json();
}

async function answerCallback(callbackId) {
  await fetch(`${API_URL}/answerCallbackQuery`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ callback_query_id: callbackId })
  });
}

const mainKbd = {
  inline_keyboard: [[
    { text: '⚡ Live Telemetry', callback_data: 'cmd_status' },
    { text: '📑 Full Report',    callback_data: 'cmd_report' }
  ]]
};

function handleStart() {
  return sendMessage(`
⚙️ <b>Autonomous Heavy Industrial PMS Bot</b>
━━━━━━━━━━━━━━━━━━━━
Real-time predictive maintenance monitoring for heavy rotating machinery.

Physics-based telemetry simulation with:
• Multi-axis vibration spectral analysis (ISO 10816-3)
• Lumped-parameter thermal dynamics
• RUL estimation via exponential degradation model
• Interactive fault injection testing

<b>Available Commands:</b>
/status  — Live sensor telemetry & health index
/report  — Full diagnostic & RUL prognostics report
/start   — Show this control board`.trim(), mainKbd);
}

function handleStatus() {
  // Server-side: we don't have live simulation data.
  // Return a status message explaining the architecture and pointing to the dashboard.
  const DASHBOARD_URL = process.env.VERCEL_URL
    ? `https://${process.env.VERCEL_URL}`
    : 'https://predictive-delta.vercel.app';

  return sendMessage(`
📡 <b>LIVE MACHINERY TELEMETRY STATUS</b>
━━━━━━━━━━━━━━━━━━━━
🌐 <b>System Architecture:</b> Hardware-in-the-Loop (HIL)
⚙️ <b>Data Source:</b> Physics Simulation Engine (Browser-side)
🔄 <b>Stream:</b> Real-time 1.5s telemetry ticks

<i>Live sensor readings are generated by the physics simulation engine running in the browser dashboard. Open the dashboard to view current values:</i>

🔗 <b>Dashboard:</b> <code>${DASHBOARD_URL}</code>

<b>Commands:</b>
• /status — Refresh this panel
• /report — Get diagnostic summary`.trim(), {
    inline_keyboard: [[
      { text: '🔄 Refresh',         callback_data: 'cmd_status' },
      { text: '📑 Diagnostic Report', callback_data: 'cmd_report' }
    ]]
  });
}

function handleReport() {
  const DASHBOARD_URL = process.env.VERCEL_URL
    ? `https://${process.env.VERCEL_URL}`
    : 'https://predictive-delta.vercel.app';

  return sendMessage(`
📑 <b>PREDICTIVE DIAGNOSTICS & PROGNOSTICS</b>
━━━━━━━━━━━━━━━━━━━━
🏭 <b>Asset:</b> Heavy Industrial Rotating Unit #402
🔬 <b>Analysis Engine:</b> Multi-axis Physics Simulation
🌐 <b>ISO Standard:</b> ISO 10816-3 Vibration Severity

<b>Available Metrics (from dashboard):</b>
• Machine Health Index (%)
• Remaining Useful Life (RUL) in Days & Hours
• Anomaly Detection Confidence Score
• ISO 10816-3 Severity Zone
• Vibration RMS, Thermal Drift, Bearing Wear

<i>Full live diagnostic data is available on the web dashboard. Automatic emergency alerts are pushed directly from the browser simulation engine when fault thresholds are breached.</i>

🔗 <b>Dashboard:</b> <code>${DASHBOARD_URL}</code>`.trim(), {
    inline_keyboard: [[
      { text: '⚡ Live Dashboard', url: DASHBOARD_URL }
    ]]
  });
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(200).json({ ok: true, message: 'PMS Telegram Webhook Active' });
  }

  try {
    const update = req.body;

    // Text messages
    if (update.message && update.message.text) {
      const text = update.message.text.trim();
      if (text.startsWith('/start'))       await handleStart();
      else if (text.startsWith('/status')) await handleStatus();
      else if (text.startsWith('/report')) await handleReport();
    }

    // Inline button callbacks
    if (update.callback_query) {
      const cb = update.callback_query.data;
      if (cb === 'cmd_status') await handleStatus();
      else if (cb === 'cmd_report') await handleReport();
      await answerCallback(update.callback_query.id);
    }

    return res.status(200).json({ ok: true });
  } catch (err) {
    console.error('[Webhook] Error:', err);
    return res.status(200).json({ ok: false });
  }
}
